sudo: required
before_install:
  - npm install -g node-gyp
language: node_js
node_js:
  - 10
env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

cache:
  apt: true
  directories:
    - node_modules
